### ISSUE TITLE
As a Craft player, I want the mouse sensitivity to be decreased so that I can play using a mouse, not just the arrow keys.

### ISSUE THREAD

**Issue by rhartlage10** [rhartlage10/CtrlAltElite-Craft#14]

**Comment by CrimsonBlack** [comment]
so I looked into fixing the sensitivity bug and changed a bunch of things around, but the sensitivity is still super buggy even with lowered sensitivity. I have been unable to figure out what the cause of the buggy movement is stemming from.

**Comment by IndecisiveMagician** [comment]
I remember him talking in class about this problem. He said that some other students from previous years have tried to work on it but its a lot more than math than you'd originally imagine, the video should be posted on the pilot by now I think he talked about it for a good bit. I forget the exact reason why it's buggy but he definitely said it in that class.
